server:
  port: 8080

spring:
  application:
    name: genericEnrollment

  datasource:
    url: jdbc:h2:mem:enrollment
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect